const get = () => {
    const word_dictionary = {
        "contact_text1": "If you have any questions about Vedas, please fill in the required information and contact us.",
        "contact_text2": "Please note that your reply may take time or may not be possible depending on the content.",
        "contact_note": "If you have difficulty inquiring in Japanese, please enter in English. Other languages cannot be accepted.",
        "contact_item_name": "Full name",
        "contact_item_mail": "Mail address",
        "contact_item_input": "Content of inquiry",
        "contact_text3": "Collection and use of personal information",
        "contact_text4": "Please confirm our ",
        "contact_text5": "privacy policy",
        "contact_text6": ".",
        "contact_text7": "If you agree with the above, click the \"Agree and Submit\" button.",
        "contact_submit": "Agree and Submit",
        "contact_complete": "Thank you for your inquiry.",
        "how_to_use_text1": "El primer lanzamiento es visualizar la estructura de la fuente de alimentación en todo Japón.",
        "how_to_use_text2": "Es muy simple y puede comenzar a usarlo de inmediato.",
        "how_to_use_text3": "Primero, seleccionemos la unidad de agregación de año, mes, día, 1 hora.",
        "how_to_use_text4": "Por ejemplo, si selecciona el mes, puede ver los datos de energía resumidos mensualmente.",
        "how_to_use_text5": "A continuación, elija una empresa de transmisión y distribución de energía.",
        "how_to_use_text6": "Si vive en el área de Energía eléctrica de Tokyo, puede consultar Energía eléctrica de Tokyo.",
        "how_to_use_text7": "Puedes ver de qué está hecha la electricidad utilizada en la vida cotidiana.",
        "how_to_use_text8": "Está bien seleccionar \"todos\" por el momento.",
        "how_to_use_text9": "Finalmente, elija el tipo de datos.",
        "how_to_use_text10": "Veamos los lugares que te interesan.",
        "how_to_use_text11": "En este punto, se mostrará el gráfico.",
        "how_to_use_text12": "Cambiemos el período libremente y juguemos.",
        "how_to_use_text13": "Por ejemplo, puedes ver",
        "how_to_use_text14": "1. La producción solar en todo Japón está en aumento.",
        "how_to_use_text15": "2. Hokkaido, Tokio y Okinawa tienen diferentes tendencias de potencia máxima.",
        "how_to_use_text16": "3. En la jurisdicción de Kyushu Electric Power, hay días en que la energía solar constituye la mayor parte de la demanda total durante el día.",
        "how_to_use_text17": "4. Japón cubre la mayor parte de su demanda total de energía térmica.",
        "how_to_use_text18": "5. En Japón, la electricidad verde (energía hidroeléctrica, geotérmica, biomasa, solar, eólica), hidroeléctrica y solar son fuertes.",
        "how_to_use_text19": "Trate de encontrar \"!\" Acerca de su conocimiento de electricidad.",
        "about_text1": "Parece que se puede hacer algo interesante.",
        "about_text2": "Comencé con un ingeniero pensando así.",
        "about_text3": "El apodo es Vedas.",
        "about_text4": "Este producto visualiza los datos de electricidad de Japón.",
        "about_text5": "Al principio, pensé en leer las iniciales de Supply And Demand Viewer desde atrás para hacerlo Vdas,",
        "about_text6": "Como ya se usaba en productos en el mundo, puse Energy E en Vedas.",
        "about_text7": "Veda es la literatura más antigua de la India, supuestamente compilada en la antigua India.",
        "about_text8": "La palabra Veda significa conocimiento.",
        "about_text9": "Con el significado del plural allí, agregue sy es Vedas.",
        "jurisdiction": "Jurisdicción",
        "watchout": "Things to watch out for",
        "watchout_info1": "The Company shall not be liable for any life, physical or property loss or damage incurred by the user of this application",
        "watchout_info2": "due to actions that depend on this application or rely on the information of this application.",
        "watchout_info3": "The data used are the actual supply and demand results announced by general power transmission and distribution companies ",
        "watchout_info4": "based on the “System Information Disclosure Concept” of the Agency for Natural Resources and Energy, Ministry of Economy, Trade and Industry.",
        "watchout_info5": "Please check the homepage of each general power transmission and distribution company for data considerations.",
        "no_data": "No hay datos para el período objetivo.",
        "term": "Término",
        "unit_y": "Año",
        "unit_ym": "Mes",
        "unit_ymd": "Fecha",
        "unit_1h": "1 hora",
        "green": "poder verde",
        "demand": "demanda",
        "nuclear": "nuclear",
        "thermal": "potencia de fuego",
        "hydro": "hidro",
        "geothermal": "Geotérmica",
        "biomass": "biomasa",
        "solar": "solar",
        "solar_output_control": "control de salida solar",
        "wind": "viento",
        "wind_output_control": "control de salida de viento",
        "pumping": "bombeo",
        "interconnection": "línea de interconexión",
        "title": "Vedas：Gráficos de energía de Japón",
        "all": "Todos",
        "hepco": "Energía eléctrica de Hokkaido",
        "tohokuepco": "Energía eléctrica de Tohoku",
        "rikuden": "Energía eléctrica de Hokuriku",
        "tepco": "Energía eléctrica de Tokyo",
        "chuden": "Energía eléctrica de Chubu",
        "kepco": "Energía eléctrica de Kansai",
        "energia": "Energía eléctrica de Chugoku",
        "yonden": "Energía eléctrica Shikoku",
        "kyuden": "Energía eléctrica de Kyushu",
        "okiden": "Energía eléctrica de OKinawa",
        "japan": "Todo japón"
    };

    return word_dictionary;
}

export default { get }