version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - cd ./viewer/front
      - if [ -e /tmp/node_modules.tar ]; then tar xf /tmp/node_modules.tar; fi
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - tar cf /tmp/node_modules.tar node_modules
      - ls
      - cd ../
      - pwd
      - cd ../
      - pwd
artifacts:
  files:
    - '**/*'
  base-directory: ./viewer/front/build
cache:
  paths:
    - /tmp/node_modules.tar